[platformio]
default_envs = app-main

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
;设置文件系统为littlefs
board_build.filesystem = littlefs

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    ; 头文件分类子目录, 让 #include "xxx.h" 按名字直接找到
    -Iinclude/drivers
    -Iinclude/services
    -Iinclude/controllers

lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

; 正式程序
[env:app-main]
build_src_filter =
    -<*>
    +<main/>


; hello_world
[env:lab-hello_world]
build_src_filter =
    -<*>
    +<lab/hello_world.cpp>
;
; wifi扫描测验
[env:lab-wifi_scan_test]
build_src_filter =
    -<*>
    +<lab/wifi_scan_test.cpp>
;
; wifi连接测验
[env:lab-wifi_connect_test]
build_src_filter =
    -<*>
    +<lab/wifi_connect_test.cpp>
;
; led闪烁测验
[env:lab-led_blink_test]
build_src_filter =
    -<*>
    +<lab/led_blink_test.cpp>
;
; 服务器测试
[env:lab-web_server_test]
build_src_filter =
    -<*>
    +<lab/web_server_test.cpp>
;
; I2C地址扫描
[env:lab-I2C_scan_test]
build_src_filter =
    -<*>
    +<lab/I2C_scan_test.cpp>
;
; OLED显示测试
[env:lab-OLED_display_test]
build_src_filter =
    -<*>
    +<lab/OLED_display_test.cpp>
;
; DHT22温湿度读取测试
[env:lab-dht_read_test]
build_src_filter =
    -<*>
    +<lab/dht_read_test.cpp>
;
; HW-390土壤传感器读取测试
[env:lab-soil_read_test]
build_src_filter =
    -<*>
    +<lab/soil_read_test.cpp>